name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip install --user -r requirements.txt
        python DjangoWeb/manage.py makemigrations
        python DjangoWeb/manage.py migrate
        coverage run --source='.' DjangoWeb/manage.py test
        coverage report