# Generated by Django 4.1 on 2022-10-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_seat',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
