# Generated by Django 4.1 on 2022-10-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_max_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
