# Generated by Django 4.1 on 2022-09-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(default='CN000', max_length=5, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('semmester', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('seat_count', models.IntegerField(blank=True, default=0, null=True)),
                ('max_seat', models.IntegerField(blank=True, default=5, null=True)),
                ('quota', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, related_name='attendances', to='courses.course')),
            ],
        ),
    ]
