# Generated by Django 4.1.1 on 2022-09-15 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(default='CN000', max_length=5, unique=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('semmester', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('seat_count', models.IntegerField(blank=True, default=0, null=True)),
                ('max_seat', models.IntegerField(blank=True, null=True)),
                ('quota', models.BooleanField(default=True)),
                ('attendance', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('s_id', models.CharField(default='-', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deleteuser', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, related_name='attendances', to='courses.course')),
            ],
        ),
    ]
