# Generated by Django 4.1 on 2022-08-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='W_quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=64)),
                ('semester', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('quota', models.IntegerField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.w_quota'),
        ),
    ]
