# Generated by Django 4.1 on 2022-10-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_attendance_alter_course_max_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attendance',
        ),
    ]
