# Generated by Django 4.1 on 2022-09-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_w_quota_alter_course_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='quota',
        ),
        migrations.DeleteModel(
            name='W_quota',
        ),
    ]
