# Generated by Django 4.1 on 2022-09-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_quota_delete_w_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quota',
            field=models.BooleanField(default=False),
        ),
    ]
