# Generated by Django 4.1 on 2022-09-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
