name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unittest 
      run: |
        cd DjangoWeb
        pip install --user -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
        coverage run manage.py test
        coverage report
